"""Refresh .specify/memory/zeus-context.md from shared memory sources.

Reads session-memory.md and decision-log.md and writes a compact derived
context file under .specify/memory/zeus-context.md for Zeus to consult at
run start.

Designed to be invoked by the zeus-memory-context SubagentStart hook.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import UTC, datetime
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SESSION_MEMORY_FILE = "session-memory.md"
DECISION_LOG_FILE = "decision-log.md"
CONTEXT_OUTPUT_FILE = "zeus-context.md"

SESSION_SECTIONS_TO_CAPTURE: tuple[str, ...] = (
    "Current Objective",
    "Blockers",
    "Next Likely Moves",
)

MAX_DECISIONS = 5


def _extract_section(content: str, header: str) -> str | None:
    """Return the body of a Markdown ## section, or None if not found."""
    pattern = re.compile(
        r"^##\s+" + re.escape(header) + r"\s*\n(.*?)(?=^##\s|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(content)
    if not match:
        return None
    return match.group(1).strip() or None


def _table_header_line(content: str) -> str | None:
    """Return the first header row from a Markdown table in content."""
    pending: str | None = None
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        if re.match(r"^\|[-| :]+\|$", stripped):
            return pending
        pending = stripped
    return None


def _last_n_table_rows(content: str, n: int) -> list[str]:
    """Return the last n data rows from the first Markdown table in content."""
    rows: list[str] = []
    separator_seen = False
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        if re.match(r"^\|[-| :]+\|$", stripped):
            separator_seen = True
            continue
        if not separator_seen:
            continue
        rows.append(stripped)
    return rows[-n:] if n > 0 else []


def _utc_now_str() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")[:19] + "Z"


def build_context(
    session_content: str,
    decision_content: str,
    *,
    max_decisions: int = MAX_DECISIONS,
    sections: tuple[str, ...] = SESSION_SECTIONS_TO_CAPTURE,
) -> str:
    """Build the zeus-context.md content string from raw memory files."""
    parts: list[str] = [
        "<!-- auto-generated by scripts/sync_memory_context.py - do not edit manually -->",
        "# Zeus Context Snapshot",
        "",
        f"**Generated:** {_utc_now_str()}",
        "",
        "Compact derived context for Zeus to consult at run start.",
        "Authoritative source files: `session-memory.md`, `decision-log.md`.",
        "",
    ]
    for section in sections:
        extracted = _extract_section(session_content, section)
        if extracted:
            parts.extend([f"## {section}", "", extracted, ""])

    rows = _last_n_table_rows(decision_content, max_decisions)
    if rows:
        header = _table_header_line(decision_content)
        col_count = header.count("|") - 1 if header else 5
        separator = "|" + "|".join(["---"] * col_count) + "|"
        parts.append(f"## Recent Decisions (last {len(rows)})")
        parts.append("")
        if header:
            parts.append(header)
            parts.append(separator)
        parts.extend(rows)
        parts.append("")

    return "\n".join(parts)


def sync_memory_context(repo_root: Path = REPO_ROOT) -> Path:
    """Read shared memory files and write zeus-context.md. Return the output path."""
    memory_dir = repo_root / ".specify" / "memory"
    session_path = memory_dir / SESSION_MEMORY_FILE
    decision_path = memory_dir / DECISION_LOG_FILE
    output_path = memory_dir / CONTEXT_OUTPUT_FILE

    session_content = session_path.read_text(encoding="utf-8") if session_path.exists() else ""
    decision_content = decision_path.read_text(encoding="utf-8") if decision_path.exists() else ""

    context = build_context(session_content, decision_content)
    memory_dir.mkdir(parents=True, exist_ok=True)
    output_path.write_text(context, encoding="utf-8")
    return output_path


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Refresh .specify/memory/zeus-context.md")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help="Repository root (default: auto-detected from script location)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv if argv is not None else sys.argv[1:])
    output_path = sync_memory_context(repo_root=args.repo_root)
    print(f"zeus-context refreshed -> {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
