"""Tests for scripts/sync_memory_context.py."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SCRIPT_DIR = Path(__file__).resolve().parent
_MODULE_PATH = _SCRIPT_DIR / "sync_memory_context.py"

_SPEC = importlib.util.spec_from_file_location("sync_memory_context", _MODULE_PATH)
assert _SPEC is not None and _SPEC.loader is not None
_smc = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_smc)  # type: ignore[union-attr]


_SAMPLE_SESSION = """# Session Memory

## Current Objective
- Evolve the orchestration repo with Zeus as root conductor.

## Active Repositories
- review_clones/OrchestationAgentsSkillLike

## In-Flight Decisions
- Memory continuity hook work is in progress.

## Current Batch
- Memory hook implementation in progress.

## Next Likely Moves
- Run tests, update README, commit.

## Blockers
- None currently documented.
"""

_SAMPLE_DECISIONS = """# Decision Log

| Date | Scope | Decision | Rationale | Consequence |
|------|-------|----------|-----------|-------------|
| 2026-03-22 | Memory | Start file-backed memory | Low risk | No DB dependency |
| 2026-03-25 | Hook | Memory continuity hook | Deterministic | zeus-context.md refreshed |
"""


def test_build_context_includes_current_objective() -> None:
    result = _smc.build_context(_SAMPLE_SESSION, _SAMPLE_DECISIONS)
    assert "Current Objective" in result
    assert "Zeus as root conductor" in result


def test_build_context_includes_blockers() -> None:
    result = _smc.build_context(_SAMPLE_SESSION, _SAMPLE_DECISIONS)
    assert "Blockers" in result
    assert "None currently documented" in result


def test_build_context_includes_next_likely_moves() -> None:
    result = _smc.build_context(_SAMPLE_SESSION, _SAMPLE_DECISIONS)
    assert "Next Likely Moves" in result
    assert "update README" in result


def test_build_context_includes_recent_decisions() -> None:
    result = _smc.build_context(_SAMPLE_SESSION, _SAMPLE_DECISIONS)
    assert "Recent Decisions" in result
    assert "2026-03-22" in result
    assert "2026-03-25" in result


def test_build_context_includes_auto_generated_comment() -> None:
    result = _smc.build_context(_SAMPLE_SESSION, _SAMPLE_DECISIONS)
    assert "auto-generated by scripts/sync_memory_context.py" in result


def test_build_context_empty_inputs_does_not_crash() -> None:
    result = _smc.build_context("", "")
    assert "Zeus Context Snapshot" in result
    assert "auto-generated" in result


def test_extract_section_not_found_returns_none() -> None:
    result = _smc._extract_section("# Only heading\n", "Nonexistent")
    assert result is None


def test_extract_section_returns_content() -> None:
    content = "## My Section\n\nSome content here.\n\n## Next Section\nother"
    result = _smc._extract_section(content, "My Section")
    assert result == "Some content here."


def test_last_n_table_rows_returns_last_rows() -> None:
    content = (
        "| Date | Decision |\n"
        "| --- | --- |\n"
        "| 2026-01-01 | Row1 |\n"
        "| 2026-01-02 | Row2 |\n"
        "| 2026-01-03 | Row3 |\n"
    )
    rows = _smc._last_n_table_rows(content, 2)
    assert len(rows) == 2
    assert "Row3" in rows[-1]
    assert "Row2" in rows[-2]


def test_last_n_table_rows_fewer_than_n() -> None:
    content = "| Date |\n| --- |\n| 2026-01-01 |\n"
    rows = _smc._last_n_table_rows(content, 5)
    assert len(rows) == 1


def test_table_header_line_found() -> None:
    content = "| Date | Decision |\n| --- | --- |\n| row |\n"
    header = _smc._table_header_line(content)
    assert header == "| Date | Decision |"


def test_table_header_line_no_table_returns_none() -> None:
    header = _smc._table_header_line("No table here.\n")
    assert header is None


def test_sync_memory_context_writes_file(tmp_path: Path) -> None:
    memory_dir = tmp_path / ".specify" / "memory"
    memory_dir.mkdir(parents=True)
    (memory_dir / "session-memory.md").write_text(_SAMPLE_SESSION, encoding="utf-8")
    (memory_dir / "decision-log.md").write_text(_SAMPLE_DECISIONS, encoding="utf-8")

    output = _smc.sync_memory_context(repo_root=tmp_path)

    assert output == memory_dir / "zeus-context.md"
    assert output.exists()
    content = output.read_text(encoding="utf-8")
    assert "Zeus Context Snapshot" in content
    assert "Current Objective" in content
    assert "2026-03-22" in content


def test_sync_memory_context_creates_missing_memory_dir(tmp_path: Path) -> None:
    output = _smc.sync_memory_context(repo_root=tmp_path)
    assert output.exists()
    content = output.read_text(encoding="utf-8")
    assert "Zeus Context Snapshot" in content


def test_sync_memory_context_missing_source_files_does_not_raise(tmp_path: Path) -> None:
    output = _smc.sync_memory_context(repo_root=tmp_path)
    assert output.exists()


def test_sync_memory_context_overwrites_stale_file(tmp_path: Path) -> None:
    memory_dir = tmp_path / ".specify" / "memory"
    memory_dir.mkdir(parents=True)
    stale = memory_dir / "zeus-context.md"
    stale.write_text("stale content", encoding="utf-8")

    _smc.sync_memory_context(repo_root=tmp_path)

    assert "stale content" not in stale.read_text(encoding="utf-8")
    assert "Zeus Context Snapshot" in stale.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# _last_n_table_rows n=0 edge case
# ---------------------------------------------------------------------------

def test_last_n_table_rows_n_zero_returns_empty() -> None:
    """rows[-0:] is rows[0:] in Python — verify the guard produces []."""
    content = (
        "| Date | Decision |\n"
        "| --- | --- |\n"
        "| 2026-01-01 | Row1 |\n"
        "| 2026-01-02 | Row2 |\n"
    )
    rows = _smc._last_n_table_rows(content, 0)
    assert rows == []


# ---------------------------------------------------------------------------
# CLI path — main() smoke test
# ---------------------------------------------------------------------------

def test_main_returns_zero_and_writes_output_file(tmp_path: Path, capsys) -> None:
    memory_dir = tmp_path / ".specify" / "memory"
    memory_dir.mkdir(parents=True)
    (memory_dir / "session-memory.md").write_text(_SAMPLE_SESSION, encoding="utf-8")
    (memory_dir / "decision-log.md").write_text(_SAMPLE_DECISIONS, encoding="utf-8")

    exit_code = _smc.main(["--repo-root", str(tmp_path)])

    assert exit_code == 0
    output_path = memory_dir / "zeus-context.md"
    assert output_path.exists()
    captured = capsys.readouterr()
    assert "zeus-context refreshed" in captured.out
